version: '2'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data-directory:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "org.apache.zookeeper=ERROR,org.apache.kafka=ERROR, kafka=ERROR, kafka.cluster=ERROR,kafka.controller=ERROR, kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR"

  keycloak:
    image: jboss/keycloak
    # ports:
    #   - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_FRONTEND_URL: http://localhost/auth/
    volumes: 
      - keycloak-h2-directory:/opt/jboss/keycloak/standalone/data

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411



  minio:
    image: minio/minio
    command: [ "server", "/data" ]
    restart: always
    volumes:
     - minio_data:/data
    # ports:
      # - 9000:9000
      # - 9001:9001
    environment:
      MINIO_ROOT_USER: webprotege
      MINIO_ROOT_PASSWORD: webprotege

  webprotege-gwt-api-gateway:
    image: webprotege-gwt-api-gateway:0.1.1-SNAPSHOT
    # ports:
      # - 7777:7777
    depends_on:
      - kafka
      - keycloak
      - minio
      - zipkin
    environment:
      spring.kafka.consumer.bootstrap-servers: http://kafka:9092
      spring.kafka.producer.bootstrap-servers: http://kafka:9092
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/auth/realms/webprotege/protocol/openid-connect/certs
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/auth/realms/webprotege
      spring.zipkin.baseUrl: http://zipkin:9411
      logging.level.org.apache.kafka: warn
      logging.level.org.springframework.kafka: warn

  webprotege-gwt-ui:
    image: webprotege-gwt-ui:latest
    depends_on:
      - webprotege-gwt-api-gateway
    # ports:
      # - 8888:8080
    environment:
      minio.access.key: minioadmin
      minio.access.secret: minioadmin
      minio.endPoint: http://minio:9000
      webprotege.gwt-api-gateway.endPoint: http://webprotege-gwt-api-gateway:7777

  webprotege-authorization-service:
    image: webprotege-authorization-service:0.1.1-SNAPSHOT
    depends_on:
      - keycloak
      - mongo
      - kafka
      - zipkin
    environment:
      spring.data.mongodb.host: mongo
      spring.data.mongodb.database: webprotege
      keycloak.jwk-set-uri: http://keycloak:8080
      spring.kafka.consumer.bootstrap-servers: kafka:9092
      spring.kafka.producer.bootstrap-servers: kafka:9092
      spring.zipkin.baseUrl: http://zipkin:9411
      logging.level.org.apache.kafka: warn
      logging.level.org.springframework.kafka: warn

  webprotege-backend-service:
    image: webprotege-backend-service:0.1.1-SNAPSHOT
    depends_on:
      - mongo
      - kafka
      - zipkin
    environment:
      spring.data.mongodb.host: mongo
      spring.data.mongodb.database: webprotege
      spring.zipkin.baseUrl: http://zipkin:9411
      webprotege.directories.data: /srv/webprotege
      spring.kafka.consumer.bootstrap-servers: kafka:9092
      spring.kafka.producer.bootstrap-servers: kafka:9092
      logging.level.org.apache.kafka: warn
      logging.level.org.springframework.kafka: warn
    volumes:
      - webprotege-data-directory:/srv/webprotege

  nginx:
    image: webprotege-nginx:latest
    ports:
      - 80:80
    depends_on: 
      - webprotege-gwt-ui
      - keycloak

volumes:
  webprotege-data-directory:
  mongo-data-directory:
  keycloak-h2-directory:
  minio_data: